export const ROUTES = {
    DASHBOARD : '/dashboard',
    LOGIN : '/',
    MAINCATEGORY : '/mainCat',
    SUBCATEGORY : "/subCat",
    CATEGORY : "/category",
    PRODUCT_LIST : "/productList",
    PRODUCT_SINGLE : "/productsingle/:id",
    ADD_PRODUCT : "/addproduct",
    EDIT_PRODUCT : "/editproduct/:id",
    ORDERS_LIST : "/orderlist",
    ORDERVIEW : "/order-view/:orderId",
    CUSTOMERS : "/customer-list",
    CUSTOMER_VIEW : "/customer-view/:id",
    COUPONS : "/coupons",
    CAROUSEL : "/carousel",
    SUBADMIN : "/sub-admins",
    EDIT_SUBADMIN : "/edit-sub-admin/:id",
    ADDSUBADMIN : "/add-sub-admins",
    ADDCOUPON : "/addcoupon",
    EDIT_COUPON : "/admin/coupons/edit/:id",
    DEALPAGE : "/dealpage",
    ADDDEAL : "/add-dealpage",
    EDITDEAL:"/editdeal/:id",
    ACCESSPERMISSION : "/access-permission",
    HOMEOFFERADD : "/add-home-offer",
    HOMEOFFER : "/home-offer",
    REFERAL : "/refreal",
    NOTIFICATION : "/notifications",
}

export const BASE_URL = 'https://grocery-codeedex.onrender.com/api';

export const API_ENDPOINTS = {
    LOGIN: `${BASE_URL}/admin/auth/login`,
    MAINCATEGORY: `${BASE_URL}/admin/main-category`,
    CATEGORY: `${BASE_URL}/admin/category`,
    CAROUSEL : `${BASE_URL}/admin/carousel`,
    REFERAL : `${BASE_URL}/admin/coin-setting`,
    TIMEDEAL : `${BASE_URL}/admin/time-sale`,
    PRODUCT : `${BASE_URL}/admin/product`,
    SUBCATEGORY : `${BASE_URL}/admin/subcategory`,
    CUSTOMER : `${BASE_URL}/admin/user-management`,
    ORDERS : `${BASE_URL}/admin/order`,
    SUBADMIN : `${BASE_URL}/admin/sub-admin-management`,
    COUPONS : `${BASE_URL}/admin/coupon`,
    NOTIFICATION : `${BASE_URL}/admin/notification`,
}
